# Generated by Django 3.1.3 on 2020-11-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('univ', models.TextField()),
                ('study', models.TextField()),
                ('other', models.TextField()),
                ('first_meet', models.TextField()),
                ('wanna_do', models.TextField()),
                ('summary', models.TextField()),
                ('isOpen', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='daily',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daily.evaluation'),
        ),
    ]
