# Generated by Django 3.1.3 on 2020-12-07 15:42

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20201123_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='first_meet',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='daily',
            name='other',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='daily',
            name='study',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='daily',
            name='summary',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='daily',
            name='univ',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='daily',
            name='wanna_do',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
