# Generated by Django 2.2.16 on 2021-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0005_auto_20201208_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
