# Generated by Django 2.2.16 on 2021-01-12 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 1, 16, 44, 551935)),
        ),
    ]
