# Generated by Django 2.2.16 on 2021-01-12 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0007_auto_20210113_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 1, 28, 27, 45492)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.CharField(max_length=50),
        ),
    ]
