# Generated by Django 2.2.16 on 2021-01-13 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0008_auto_20210113_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='oshi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 2, 14, 0, 161239)),
        ),
    ]
