# Generated by Django 2.2.16 on 2021-01-15 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0009_auto_20210114_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 2, 7, 55, 555413)),
        ),
    ]
